### PR TITLE
Add neovim as pager

### PR DESCRIPTION
**Pull request by z33ky**

### CODE REVIEW

**Comment by aitjcize** [comment]
Couldn't you just alias  vim as `nvim`? or simply set the PAGER variable.

**Comment by z33ky** [comment]
Aliases are generally not respected in shell scripts, unless the system-wide configuration is changed accordingly. I could add a symlink and add its directory to the PATH environment variable.
Just setting PAGER could work, though I would also need to ensure I keep up-to-date with the flags as passed to `vim`.

**Comment by belkka** [comment]
I have no vim installed (nvim only), but cppman just works.

**Comment by z33ky** [comment]
Well it has a fallback to `less`. Do you mean by _works_ that it shows something or does it start `nvim` for you?

**Comment by belkka** [comment]
It actually starts neovim. I run `$ cppman vector`, then type `:version<CR>` and it shows a message
> NVIM 0.1.7                                                                          
> Build type: None                                                                    
> Compilation: /usr/bin/cc -g -O2 <a lot of options>...

**Comment by z33ky** [comment]
Weird. I just compiled cppman from git, but I still get `less`, even after `cppman -p vim`.
What's the output of `which vim && readlink -e "$(which vim)"` on your system?

**Comment by belkka** [comment]
```
$ link="$(which vim)"; while true; do echo "$link -> "; link="$(readlink "$link")" || break; done
/usr/bin/vim -> 
/etc/alternatives/vim -> 
/usr/bin/nvim -> 
```

Vim is not installed, nvim is

**Comment by z33ky** [comment]
My distro doesn't have an alternatives system that sets up such symlinks.
In the hypothetical scenario where you have both neovim and vim installed, there would be no way of selecting either editor without changing the (global) symlink as well.

As mentioned before, one can still create a symlink in a private directory and add it to `PATH`, though then launching (non-neo)vim from a shell would be awkward, though not a common use-case I guess.

I do not see the issue with my proposed changes though.

**Comment by aitjcize** [comment]
you can just set your `PAGER` environment variable to `nvim` and it should just work.

**Pull request closed without merging**
