### PR TITLE
Migrate to Python3

### PR DESCRIPTION
**Pull request by czchen**
This pull request migrate cppman to Python3.

### CODE REVIEW

**Comment by aitjcize** [comment]
I actually want cppman to work with both python2 and python3. Do you think that's a good idea?

**Comment by czchen** [comment]
I am not sure if it is necessary to support both python2 and python3 at the same time for an application. However, If support both python2 and python3 at the same code base is needed, maybe we can use [six](https://pypi.python.org/pypi/six/) to do so. I do not use [six](https://pypi.python.org/pypi/six/) before, but the API document seem to address most of the code changed by `2to3`.

Also, we need to setup [tox](https://pypi.python.org/pypi/tox) to easily test code in both python2 and python3 at the same time. I will to a PR for tox later.

**Comment by aitjcize** [comment]
Yes you have a point, since we are just an application. It really doesn't matter how it's implemented. I'm going to merge this PR into a testing branch. Can you fixup the things I mentioned in the commits? Thanks a lot!

**Comment by czchen** [comment]
All the comments are fixed. Please help to test it, thanks.

**Comment by aitjcize** [comment]
Pushed into the python3 branch for now. I'll do more testing this week, if everything is fine I'll merge it into master. (Merging into other branch doesn't seem to close the PR)

**Comment by TheJJ** [comment]
I'd also be interested in seeing cppman support python 3. How's the status of this now?

**Comment by aitjcize** [comment]
This seems to be stable enough.

**Comment by czchen** [comment]
@aitjcize Please release a new version for this so that others can help to test if there is any problem in Python3.

**Comment by aitjcize** [comment]
Yes I was about to do that.

**Comment by aitjcize** [comment]
version 0.4.5 released

**Pull request merged**
