### PR TITLE
add support for Python2.7

### PR DESCRIPTION
**Pull request by guohengkai**
Tested at Python 2.7.

### CODE REVIEW

**Comment by aitjcize** [comment]
Does the crawler works with 2.7? I remember doing this a long time ago and the parser need some extra changes.

**Comment by guohengkai** [comment]
@aitjcize I'm not sure, but the main program can be used in Python 2.7 on my Mac OS without any errors. Could you verify it? Or just provide some tests for the crawler?

**Comment by SGSSGene** [comment]
I think it's not worth it anymore to revive `cppman` for `python2`. Pythons2 life time is ending at the end of this year. https://pythonclock.org/

**Comment by guohengkai** [comment]
@SGSSGene Yes, that makes sense.

**Pull request closed without merging**
